PyPI Project Name (required)
data-understanding-du
The project that will be created on PyPI when this publisher is used

Owner (required)
uvpatel
The GitHub organization name or GitHub username that owns the repository

Repository name (required)
DU
The name of the GitHub repository that contains the publishing workflow

Workflow name (required)
pyproject.toml
The filename of the publishing workflow. This file should exist in the .github/workflows/ directory in the repository configured above.

Workflow name must end with .yml or .yaml
Environment name (optional)
pypi
The name of the GitHub Actions environment that the above workflow uses for publishing. This should be configured under the repository's settings. While not required, a dedicated publishing environment is strongly encouraged, especially if your repository has maintainers with commit access who shouldn't have PyPI publishing access.


Help